from graphics import *

def main():
    win = GraphWin()
    one = Rectangle(Point(10,10), Point(40, 40))
    one.setOutline("black")
    one.draw(win)
    two = Rectangle(Point(45, 10), Point(75, 40))
    two.setOutline("black")
    two.draw(win)
    three = Rectangle(Point(80, 10), Point(110, 40))
    three.setOutline("black")
    three.draw(win)
    four = Rectangle(Point(115, 10), Point(145, 40))
    four.setOutline("black")
    four.draw(win)
    five = Rectangle(Point(150, 10), Point(180, 40))
    five.setOutline("black")
    five.draw(win)
    onedo = Circle(Point(25,25), 1)
    onedo.setOutline("black")
    onedo.setFill("black")
    onedo.draw(win)
    twodo = Circle(Point(65,20), 1)
    twodo.setOutline("black")
    twodo.setFill("black")
    twodo.draw(win)
    twodos = Circle(Point(55,30), 1)
    twodos.setOutline("black")
    twodos.setFill("black")
    twodos.draw(win)
    threedo = Circle(Point(95,25), 1)
    threedo.setOutline("black")
    threedo.setFill("black")
    threedo.draw(win)
    threedos = Circle(Point(100,20), 1)
    threedos.setOutline("black")
    threedos.setFill("black")
    threedos.draw(win)
    threedose = Circle(Point(90,30), 1)
    threedose.setOutline("black")
    threedose.setFill("black")
    threedose.draw(win)
    fourdo = Circle(Point(125,20), 1)
    fourdo.setOutline("black")
    fourdo.setFill("black")
    fourdo.draw(win)
    fourdos = Circle(Point(135,30), 1)
    fourdos.setOutline("black")
    fourdos.setFill("black")
    fourdos.draw(win)
    fourdose = Circle(Point(135,20), 1)
    fourdose.setOutline("black")
    fourdose.setFill("black")
    fourdose.draw(win)
    fourdoset = Circle(Point(125,30), 1)
    fourdoset.setOutline("black")
    fourdoset.setFill("black")
    fourdoset.draw(win)
    fivedo = Circle(Point(165,25), 1)
    fivedo.setOutline("black")
    fivedo.setFill("black")
    fivedo.draw(win)
    fivedos = Circle(Point(160,30), 1)
    fivedos.setOutline("black")
    fivedos.setFill("black")
    fivedos.draw(win)
    fivedose = Circle(Point(160,20), 1)
    fivedose.setOutline("black")
    fivedose.setFill("black")
    fivedose.draw(win)
    fivedoset = Circle(Point(170,20), 1)
    fivedoset.setOutline("black")
    fivedoset.setFill("black")
    fivedoset.draw(win)
    fivedoseto = Circle(Point(170,30), 1)
    fivedoseto.setOutline("black")
    fivedoseto.setFill("black")
    fivedoseto.draw(win)
                    
main()
